services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # В CI не мапим порты чтобы избежать конфликтов
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Оставляем только бэкенд порт
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/auth_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network

  tests:
    build: ./tests
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      TEST_BASE_URL: http://backend:8000

networks:
  app-network:
    driver: bridge